---
title: "Watson_Opt"
output: html_document
date: "2022-12-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(rgdal)          
library(ggplot2)      
library(dplyr)
library(tidyr)
library(readr)
library(sf)
library(gdistance)
library(gstat)
library(sp)
library(scales)
library(magrittr)
library(automap)
library(ResistanceGA)
library(tidyverse)
library(terra)
library(ecodist)
library(Matrix)
library(tictoc)
```

##Data and set up files
```{r raw data rasters}
#This data is for optimization of ONLY STREAMS
#Therefore, all data was masked by NHDPlus streams

#In-stream conductivity measurements. Cells of streams without measurements were assigned a value of 100
Cond<-raster("RGAfiles/Cond_Rescaled_Conduct.tif")
plot(Cond)
Cond

#Percent forest cover created reclassifying NLCD raster to only have forest valus, then by doing a moving window analysis of 5x5
NLCD<-raster("RGAfiles/RawNLCD_Masked_Clip21.tif")
plot(NLCD)
NLCD

#Flow accumulation raster from NHDPlus as a proxy for StreamSize
SS<-raster("RGAfiles/SS_Rescaled_Conduct.tif")
plot(SS)
SS

#Slope raster from NHDPlus
Slope<-raster("RGAfiles/Slope_Rescaled_Conduct.tif")
plot(Slope)
Slope

#Elev raster from NHDPlus
Elev<-raster("RGAfiles/Elev_Rescaled_Conduct.tif")
plot(Elev)
Elev

#Culvert AOP score as assigned by SARP protocol, cells without culverts were assigned a value of 100, AOP scores were scaled from 0-1 to 1-100
Culv<-raster("RGAfiles/AOPScaled4_Clip21.tif")
plot(Culv)
Culv


```

```{r run before optimization}
write.dir <- "C:/Users/rwatson17/Desktop/Watson_Opt/MS/"
write.dir<-"C:/Users/rwatson17/Desktop/Test5/"
# Give path to CIRCUITSCAPE .exe file
CS.program <- paste('"C:/Program Files/Circuitscape/cs_run.exe"')
JULIA_HOME <- "C:/Program Files/Julia-1.8.5/bin"
JuliaCall::julia_setup(JULIA_HOME)
#fst
library(hierfstat)
library(adegenet)
Data <- read.genepop("RGAfiles/KAD_Watson_GenepopFile_12popNo519.gen") 
Datahier <- genind2hierfstat(Data)
wcpw <-pairwise.WCfst(Datahier, diploid = TRUE)
wcpw<-lower(wcpw)
#sites
samples<-read_csv("RGAfiles/SitesUTM_noLD.csv")
write.table(samples,file=paste0(write.dir,"samples.txt"),sep="\t",col.names=F,row.names=F)
sample.locales <- SpatialPoints(samples[,c(2,3)])

```

##Single Surface Optimization with commuteDistance
```{r SS optim with commuteDistance}
tic()
#Continuous rasters

#Cond
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program, response = wcpw)
#Run_CS will create an .asc file in your export directory for GA.prep to use, therefore export directory of Run_CS has to be the same as ASCII directory of GA.prep
#Make sure there is only one .asc file in your ASCII directory
CS.response1 <- Run_CS(CS.inputs = CS.inputs, r= SS, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Test5/")
GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Cond/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Cond/", max.cat = 100, max.cont = 100,
parallel = 6)

gdist.inputs1 <- gdist.prep(length(sample.locales),
samples = sample.locales,
response = CS.response1,
method = 'commuteDistance')

SS_RESULTS.gdist1 <- SS_optim(gdist.inputs = gdist.inputs1,
GA.inputs = GA.inputs)

#NLCD
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir4,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response3 <- Run_CS(CS.inputs = CS.inputs, r= NLCD, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/NLCD/")
GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/NLCD/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/NLCD/", max.cat = 100, max.cont = 100,
parallel = 6)

gdist.inputs3 <- gdist.prep(length(sample.locales),
samples = sample.locales,
response = CS.response3,
method = 'commuteDistance')

SS_RESULTS.gdist3 <- SS_optim(gdist.inputs = gdist.inputs3,
GA.inputs = GA.inputs)


#SS
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir4,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response4 <- Run_CS(CS.inputs = CS.inputs, r= SS, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/SS/")
GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/SS/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/SS/", max.cat = 100, max.cont = 100,
parallel = 6)

gdist.inputs4 <- gdist.prep(length(sample.locales),
samples = sample.locales,
response = CS.response4,
method = 'commuteDistance')

SS_RESULTS.gdist4 <- SS_optim(gdist.inputs = gdist.inputs4,
GA.inputs = GA.inputs)


#Slope
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir4,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response5 <- Run_CS(CS.inputs = CS.inputs, r= Slope, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Slope/")
GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Slope/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Slope/", max.cat = 100, max.cont = 100,
parallel = 6)

gdist.inputs5 <- gdist.prep(length(sample.locales),
samples = sample.locales,
response = CS.response5,
method = 'commuteDistance')

SS_RESULTS.gdist5 <- SS_optim(gdist.inputs = gdist.inputs5,
GA.inputs = GA.inputs)


#Elev
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir4,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response6 <- Run_CS(CS.inputs = CS.inputs, r= Elev, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Elev/")
GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Elev/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Elev/", max.cat = 100, max.cont = 100,
parallel = 6)

gdist.inputs6 <- gdist.prep(length(sample.locales),
samples = sample.locales,
response = CS.response6,
method = 'commuteDistance')

SS_RESULTS.gdist6 <- SS_optim(gdist.inputs = gdist.inputs6,
GA.inputs = GA.inputs)

#Categorical raster

Culv<-raster("RGAfiles/AOPScaled2.tif")
write.dir<-"C:/Users/rwatson17/Desktop/Watson_OptCD/"
write.dir3<-"C:/Users/rwatson17/Desktop/Watson_OptCD2/"
#Culv
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response7 <- Run_CS(CS.inputs = CS.inputs, r= Culv, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD/Culv/")

GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD/Culv/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD/Culv/", max.cat = 100, max.cont = 100,
parallel = 6)

gdist.inputs7 <- gdist.prep(length(sample.locales),
samples = sample.locales,
response = CS.response7,
method = 'commuteDistance')

SS_RESULTS.gdist7 <- SS_optim(gdist.inputs = gdist.inputs7,
GA.inputs = GA.inputs)

toc()
#Run SS_optim twice to make sure you get the same outputs each time (compare ContinuousResults.csv s or CategoricalResults.csv s)
#If you do not get the same results, run SS_optim until two match up and have the lowest AIC/LL

#The outputs in the Cat/ContResults.csv are the numbers you put into the PARM line of Combine_Surfaces in MS.optim
```

##Multi Surface Optimization with CS through Julia

```{r MS optim CS julia}

# Directory to write .asc files and results
write.dir<-"C:/Users/rwatson17/Desktop/Test5/"

#Create raster stack
r.stack<-stack(Culv,Cond,Elev,NLCD,Slope,SS)
r.stack

GA.inputs <- GA.prep(ASCII.dir = r.stack,
Results.dir = write.dir,
method = "LL",
max.cat = 100,
max.cont = 100,
parallel = 12)

jl.inputs <- jl.prep(n.Pops = length(sample.locales),
                     response = wcpw,
                     CS_Point.File = sample.locales,
                     JULIA_HOME = JULIA_HOME, cholmod = TRUE)

Multi.Surface_optim <- MS_optim(jl.inputs = jl.inputs,
GA.inputs = GA.inputs)
```
```{r all comb}
# Directory to write .asc files and results
write.dir<-"C:/Users/rwatson17/Desktop/All/"
#Create raster stack
r.stack<-stack(Culv,Cond,Elev,NLCD,Slope,SS)

GA.inputs <- GA.prep(ASCII.dir = r.stack,
Results.dir = all.comb,
method = "LL",
max.cat = 100,
max.cont = 100,
parallel = 12)

jl.inputs <- jl.prep(n.Pops = length(sample.locales),
                     response = wcpw,
                     CS_Point.File = sample.locales,
                     JULIA_HOME = JULIA_HOME, cholmod = TRUE)

all.comb<-all_comb(jl.inputs = jl.inputs,
GA.inputs = GA.inputs,write.dir, max.combination = 6, dist_mod = FALSE)
```


##SS optim with Circuitscape-slower way
```{r SS optim Circuitscape}
tic() #times the run
#Culv
CS.response1 <- Run_CS(CS.inputs = CS.inputs, r=Culv, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Culv/")
#rerun GA.prep with new .asc file
GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Culv/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Culv/", max.cat = 100,
method = "LL",
parallel = 6)

#Rerun CS.prep including the newly created CS.response
CS.inputs1 <- CS.prep(n.Pops = length(sample.locales),
response = CS.response1,
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program)

SS_RESULTS <- SS_optim(CS.inputs=CS.inputs1,
GA.inputs=GA.inputs)

# Cond
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response2 <- Run_CS(CS.inputs = CS.inputs, r= Cond, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Cond/")

GA.inputs <- GA.prep(ASCII.dir = write.dir, Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Cond/", max.cat = 100,
method = "LL",
parallel = 6)

CS.inputs2 <- CS.prep(n.Pops = length(sample.locales),
response = CS.response2,
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program)

SS_RESULTS2 <- SS_optim(CS.inputs=CS.inputs2,
GA.inputs=GA.inputs)

#NLCD
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response3 <- Run_CS(CS.inputs = CS.inputs, r= NLCD, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/NLCD/")

GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/NLCD/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/", max.cat = 100,
method = "LL",
parallel = 6)

CS.inputs3 <- CS.prep(n.Pops = length(sample.locales),
response = CS.response3,
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program)

SS_RESULTS3 <- SS_optim(CS.inputs=CS.inputs3,
GA.inputs=GA.inputs)

#SS
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response4 <- Run_CS(CS.inputs = CS.inputs, r= SS, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/SS/")

GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/SS/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/SS/", max.cat = 100,
method = "LL",
parallel = 6)

CS.inputs4 <- CS.prep(n.Pops = length(sample.locales),
response = CS.response4,
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program)

SS_RESULTS4 <- SS_optim(CS.inputs=CS.inputs4,
GA.inputs=GA.inputs)

#Slope
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response5 <- Run_CS(CS.inputs = CS.inputs, r= Slope, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Slope/")

GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Slope/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Slope/", max.cat = 100,
method = "LL",
parallel = 6)

CS.inputs5 <- CS.prep(n.Pops = length(sample.locales),
response = CS.response5,
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program)

SS_RESULTS5 <- SS_optim(CS.inputs=CS.inputs5,
GA.inputs=GA.inputs)

#Elev
CS.inputs <- CS.prep(n.Pops = length(sample.locales),
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program, response = wcpw)

CS.response6 <- Run_CS(CS.inputs = CS.inputs, r= Elev, CurrentMap = TRUE, EXPORT.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Elev/")

GA.inputs <- GA.prep(ASCII.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Elev/", Results.dir = "C:/Users/rwatson17/Desktop/Watson_OptCD3/Elev/", max.cat = 100,
method = "LL",
parallel = 6)

CS.inputs6 <- CS.prep(n.Pops = length(sample.locales),
response = CS.response6,
CS_Point.File = paste0(write.dir,"samples.txt"),
CS.program = CS.program)

SS_RESULTS6 <- SS_optim(CS.inputs=CS.inputs6,
GA.inputs=GA.inputs)
toc()
```